swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "2.0.0"
  title: Swagger REST API 
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /posts:
    get:
      operationId: "posts_v2.read"
      tags:
        - "Posts"
      summary: "The posts data structure supported by the server application"
      description: "Read the list of posts"
      responses:
        200:
          description: "Successful read posts list operation"
          schema:
            type: "array"
            items:
              properties:
                pet_id:
                  type: "integer"
                  example: 1
                petname:
                  type: "string"
                  example: "doggy"
                category:
                  type: "string"
                  example: "dogs"
                breed:
                  type: "string"
                  example: "Pomsky?"
                url:
                  type: "string"
                  example: "http://www.example.com"
                body:
                  type: "string"
                  example: "pomsky are pretty subborn?"
                timestamp:
                  type: "string"
                  example: "2021-03-27 20:10:09"
                version:
                  type: "number"
                  example: 2.0