"""add link post feature

Revision ID: 066a2dcdad29
Revises: 299114eddda7
Create Date: 2018-09-02 08:06:31.623021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "066a2dcdad29"
down_revision = "299114eddda7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("link", sa.Boolean(), nullable=True))
    op.add_column("post", sa.Column("url", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "url")
    op.drop_column("post", "link")
    # ### end Alembic commands ###
