"""empty message

Revision ID: 8d7f5540133a
Revises: 93b501c2e5f6
Create Date: 2018-08-30 16:18:14.704176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d7f5540133a"
down_revision = "93b501c2e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_vote",
        sa.Column("user.id", sa.Integer(), nullable=False),
        sa.Column("comment.id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["comment.id"], ["comment.id"]),
        sa.ForeignKeyConstraint(["user.id"], ["user.id"]),
        sa.PrimaryKeyConstraint("user.id", "comment.id"),
    )
    op.add_column("comment", sa.Column("vote_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comment", "vote_count")
    op.drop_table("comment_vote")
    # ### end Alembic commands ###
