"""new fields in user model

Revision ID: 73de38122348
Revises: c24a96b36ed2
Create Date: 2018-06-26 09:28:17.174183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73de38122348"
down_revision = "c24a96b36ed2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    # ### end Alembic commands ###
