"""empty message

Revision ID: 8c4cf25f4e2b
Revises: d09178809d5e
Create Date: 2018-08-27 11:43:08.721111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c4cf25f4e2b"
down_revision = "d09178809d5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_category_title"), "category", ["title"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_category_title"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
