"""empty message

Revision ID: e4278061c9f1
Revises: 73de38122348
Create Date: 2018-08-21 13:07:00.422283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4278061c9f1"
down_revision = "73de38122348"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("vote_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "vote_count")
    # ### end Alembic commands ###
